catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import MainConfig
from catalog.views import contacts, product_card, ProductListView, ProductDetailView, \
    CategoryListView, ReviewListView, ReviewCreateView, ReviewDetailView, ReviewUpdateView, ReviewDeleteView, IndexView, \
    ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = MainConfig.name

urlpatterns = [
    path('', contacts, name='contacts'),
    path('ind/', IndexView.as_view(), name='index'),
    path('prod_list/', ProductListView.as_view(), name='products_list'),
    path('<int:pk>/prod_card/', product_card, name='product_card'),
    path('cat/', CategoryListView.as_view(), name='categories'),
    path('<int:pk>/detail/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('reviews_lst/', ReviewListView.as_view(), name='reviews'),
    path('create_review/', ReviewCreateView.as_view(), name='create_review'),
    path('review_detail/<int:pk>/', ReviewDetailView.as_view(), name='review_detail'),
    path('review_edit/<int:pk>/', ReviewUpdateView.as_view(), name='review_edit'),
    path('review_delete/<int:pk>/', ReviewDeleteView.as_view(), name='delete_review'),
    path('prod_create/', ProductCreateView.as_view(), name='product_create'),
    path('prod_update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('prod_delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name='Почта', unique=True)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='Страна', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class UserUpdateForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'avatar', 'phone', 'country']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserUpdateForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Вход</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Войти</button>
                        <a type="button" class="btn btn-danger" href="{% url 'catalog:contacts' %}"> Отмена</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}

            <div class="col-12">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="col-3"></div>
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Регистрация</h3>
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                                <a type="button" class="btn btn-danger" href="{% url 'catalog:contacts' %}"> Отмена</a>
                            </div>
                        </div>
                    </div>
                </form>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}

            <div class="col-12">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="col-3"></div>
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Профиль</h3>
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">Сохранить</button>
                                <a type="button" class="btn btn-danger" href="{% url 'catalog:index' %}"> Отмена</a>
                            </div>
                        </div>
                    </div>
                </form>
    </div>
{% endblock %}