catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import MainConfig
from catalog.views import contacts, product_card, ProductListView, ProductDetailView, \
    CategoryListView, ReviewListView, ReviewCreateView, ReviewDetailView, ReviewUpdateView, ReviewDeleteView, IndexView, \
    ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = MainConfig.name

urlpatterns = [
    path('', contacts, name='contacts'),
    path('ind/', IndexView.as_view(), name='index'),
    path('prod_list/', ProductListView.as_view(), name='products_list'),
    path('<int:pk>/prod_card/', product_card, name='product_card'),
    path('cat/', CategoryListView.as_view(), name='categories'),
    path('<int:pk>/detail/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('reviews_lst/', ReviewListView.as_view(), name='reviews'),
    path('create_review/', ReviewCreateView.as_view(), name='create_review'),
    path('review_detail/<int:pk>/', ReviewDetailView.as_view(), name='review_detail'),
    path('review_edit/<int:pk>/', ReviewUpdateView.as_view(), name='review_edit'),
    path('review_delete/<int:pk>/', ReviewDeleteView.as_view(), name='delete_review'),
    path('prod_create/', ProductCreateView.as_view(), name='product_create'),
    path('prod_update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('prod_delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

catalog/models.py
from django.conf import settings
from django.db import models, connection
from django.db.models.signals import post_save
from django.dispatch import receiver

NULLABLE = {
    'blank': True,
    'null': True,
}


class Category(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    category_name = models.CharField(max_length=50, verbose_name='Категория')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('category_name',)

    @classmethod
    def truncate_table_restart_id(cls):
        with connection.cursor() as cursor:
            cursor.execute(f'TRUNCATE TABLE {cls._meta.db_table} RESTART IDENTITY CASCADE')


class Product(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    img = models.ImageField(upload_to='product/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    cost = models.IntegerField(verbose_name='Цена')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='user', **NULLABLE)
    first_date = models.DateTimeField(verbose_name='Дата создания', **NULLABLE)
    last_date = models.DateTimeField(verbose_name='Дата изменения', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='В наличии', **NULLABLE)
    can_be_ordered = models.BooleanField(default=True, verbose_name='Можно заказать', **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='опубликован', **NULLABLE)

    def __str__(self):
        return f'{self.name} | {self.category} | {self.cost} руб.'

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ('category',)


class Review(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(unique=True, max_length=100, verbose_name='slug', **NULLABLE)
    text = models.TextField(verbose_name='Содержимое')
    photo = models.ImageField(upload_to='review/', verbose_name='Первью', **NULLABLE)
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return f'Отзыв {self.title}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number = models.IntegerField(verbose_name='Номер версии')
    name = models.CharField(max_length=100, verbose_name='Название версии')
    sign = models.BooleanField(default=False, verbose_name='Текущая версия', **NULLABLE)

    def __str__(self):
        return f'Продукт {self.product} версии {self.number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'


# @receiver(post_save, sender=Version)
# def set_current_version(sender, instance, **kwargs):
#     if instance.current_version:
#         Version.objects.filter(product=instance.product).exclude(pk=instance.pk).update(current_version=False)

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('user', 'is_active',)

    censored = ['казино',
                'криптовалюта',
                'крипта',
                'биржа',
                'дешево',
                'бесплатно',
                'обман',
                'полиция',
                'радар'
                ]

    def clean_product_name(self):
        cleaned_data = self.cleaned_data.get('name')
        for word in self.censored:
            if word in cleaned_data:
                raise forms.ValidationError('Недопустимое слово!')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        for word in self.censored:
            if word in cleaned_data:
                raise forms.ValidationError(f'Недопустимое слово - {word}!')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class ModeratorProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')

catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Permission
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from catalog.forms import ProductForm, VersionForm, ModeratorProductForm
from catalog.models import Product, Category, Review, Version
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify

from catalog.services import get_cache_version_for_product, get_cache_for_categories


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'catalog/index.html'
    extra_context = {
        'title': 'Главная',
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Product.objects.all()[:3]
        return context_data


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    login_url = 'users:login'
    template_name = 'catalog/products_list.html'

    # def get_queryset(self):
    #     queryset = super().get_queryset().all()
    #     if not self.request.user.is_staff:
    #         return queryset.filter(user=self.request.user, is_published=True)
    #     return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['version'] = Version.objects.all()
        context['title'] = 'Все товары'
        return context


def contacts(request):
    context = {
        'title': 'O.S.Ky: Вход/Регистрация'
    }
    return render(request, 'catalog/contacts.html', context)


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'catalog/categories.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['object_list'] = get_cache_for_categories()
        context_data['title'] = 'Категории'
        return context_data


@login_required
def product_card(request, pk):
    category_item = Category.objects.get(pk=pk)
    context = {
        'object_list': Product.objects.filter(category_id=pk),
        'title': f'Товары категории {category_item.category_name}'
    }

    return render(request, 'catalog/product_card.html', context)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['versions'] = get_cache_version_for_product(self.object.pk)
        return context_data


class ReviewListView(ListView):
    model = Review
    template_name = 'catalog/review_list.html'
    extra_context = {
        'title': 'Все отзывы'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class ReviewCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Review
    permission_required = 'catalog.add_review'
    fields = ('title', 'text', 'photo', 'is_published')
    success_url = reverse_lazy('catalog:reviews')
    extra_context = {
        'title': 'Написать отзыв'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_review = form.save()
            new_review.slug = slugify(new_review.title)
            new_review.save()
        return super().form_valid(form)


class ReviewUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Review
    permission_required = 'catalog.change_review'
    fields = ('title', 'slug', 'text', 'photo')

    def form_valid(self, form):
        if form.is_valid():
            new_review = form.save()
            new_review.slug = slugify(new_review.title)
            new_review.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:review_detail', args=[self.kwargs.get('pk')])


class ReviewDetailView(DetailView):
    model = Review
    template_name = 'catalog/review_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ReviewDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Review
    permission_required = 'catalog.delete_review'
    success_url = reverse_lazy('catalog:reviews')


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'

    def get_success_url(self):
        # return reverse('catalog:product_card', args=[self.kwargs.get('pk')])
        return reverse('catalog:products_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    login_url = 'users:login'
    permission_required = 'catalog.change_product'

    def get_form_class(self):
        if self.request.user.is_superuser:
            return ProductForm
        return ModeratorProductForm

    def get_success_url(self):
        # return reverse('catalog:product_card', args=[self.kwargs.get('pk')])
        return reverse('catalog:products_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404("Вы не являетесь владельцем этого товара")
        return self.object


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    login_url = 'users:login'
    success_url = reverse_lazy('catalog:products_list')

    def test_func(self):
        return self.request.user.is_superuser

catalog/templates/catalog/index.html
{% load static %}
{% load my_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">O.S.Ky</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
        <div class="btn-group">
            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown"
                    aria-expanded="false">
                Меню
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'catalog:categories' %}">Категории</a></li>
                <li><a class="dropdown-item" href="{% url 'catalog:products_list' %}">Все товары</a></li>
                <li><a class="dropdown-item" href="#">Мастерская</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Стать партнёром</a></li>
            </ul>
        </div>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Личный кабинет</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">O.S.Ky</h1>
    <p class="lead">O.S.Ky - это прекрасная возможность заказать всё в одном месте, и не только!</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="container">
            <center>
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Образцы товаров</h4>
                    </div>
                    <center>
                        <div class="card" style="width: 18rem;">
                            {% for object in object_list %}
                                <img src="{{ object.img|mymedia }}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">{{ object.name }}</h5>
                                    <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                                    <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-primary">К
                                        товару</a>
                                </div>
                            {% endfor %}
                        </div>
                    </center>
                </div>
            </center>
            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        O.S.Ky
                        <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Путеводитель</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Товары в наличии</a></li>
                            <li><a class="text-muted" href="#">Товары под заказ</a></li>
                            <li><a class="text-muted" href="#">Полезно знать</a></li>
                            <li><a class="text-muted" href="#">Частые вопросы</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Дополнительно</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Мы пишем</a></li>
                            <li><a class="text-muted" href="{% url 'catalog:products_list' %}">Предложить свой товар</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>О нас</h5>
                        <p>

                            <a class="p-2 btn btn-primary" href="{% url 'catalog:reviews' %}">Отзывы</a>

                            <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseWidthExample" aria-expanded="false"
                                    aria-controls="collapseWidthExample">
                                Контакты
                            </button>
                        </p>
                        <div style="min-height: 120px;">
                            <div class="collapse collapse-horizontal" id="collapseWidthExample">
                                <div class="card card-body" style="width: 300px;">
                                    <code>E-mail</code> Lucifer@666.hell<br/>
                                    <code>Телефон</code> 6271-6973-6491<br/>
                                    <code>Дополнительные ссылки</code> www.asmodey.hell
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </footer>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                crossorigin="anonymous"></script>
    </div>
</div>
</body>
</html>

catalog/templates/catalog/product_card.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}


    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for object in object_list %}

                    <div class="col">
                        <div class="card shadow-sm" style="width: 18rem;">
                            <img src="{{ object.img|mymedia }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <p class="card-text">{{ object|title }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a type="button" class="btn btn-sm btn-outline-secondary"
                                           href="{% url 'catalog:product_detail' object.pk %}">К
                                            товару</a>
                                        <a type="button" class="btn btn-sm btn-outline-secondary"
                                           href="{% url 'catalog:categories' %}">К
                                            категориям</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container col-3">
            <div class="row">
                <div class="col-auto">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить товар "{{ object.title }}"?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-success">Отменить</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ object.name }}</h1>
            </div>
        </div>
    </section>
    <div class="container">
        <div class="row g-0 bg-body-secondary position-relative">
            <div class="col-md-6 mb-md-0 p-md-4">
                <img src="{{ object.img|mymedia }}" class="w-100" alt="...">
            </div>
            <div class="col-md-6 p-4 ps-md-0">
                <table class="table">
                    <tr>
                        <td>Название</td>
                        <td>{{ object.name }}</td>
                    </tr>
                    <tr>
                        <td>id</td>
                        <td>{{ object.id }}</td>
                    </tr>
                    <tr>
                        <td>Цена</td>
                        <td>{{ object.cost }}</td>
                    </tr>
                    <tr>
                        <td>Категория</td>
                        <td>{{ object.category }}</td>
                    </tr>
                    <tr>
                        <td>Описание</td>
                        <td>{{ object.description }}</td>
                    </tr>
                    <tr>
                        <td>Влыделец</td>
                        <td>{{ object.user|default:'OS.KY' }}</td>
                    </tr>
                    <tr>
                        <td>Версия</td>
                        {% for version in versions %}
                            {% if version %}
                                <td>{{ version }}</td>
                            {% else %}
                                <td>Без версии</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    <tr>
                        <td>Наличие</td>
                        <td>
                            {% if object.is_active is True %}
                                В наличии
                            {% else %}
                                Нет в наличии
                            {% endif %}
                        </td>
                    </tr>
                    {% if object.is_active is False %}
                        <tr>
                            <td>Заказ</td>
                            <td>
                                {% if object.can_be_ordered is True %}
                                    Можно заказать
                                {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                </table>


                <button type="button" class="btn btn-success">Купить</button>
                {% if object.user == request.user or user.is_superuser or user.is_staff %}
                    {% if perms.catalog.change_product %}
                        <a type="button" class="btn btn-warning"
                           href="{% url 'catalog:product_update' object.pk %}">Изменить</a>
                    {% endif %}
                    {% if user.is_superuser %}
                        <a type="button" class="btn btn-danger"
                           href="{% url 'catalog:product_delete' object.pk %}">Удалить</a>
                    {% endif %}
                {% endif %}
                <a type="button" class="btn btn-primary"
                   href="{% url 'catalog:products_list' %}">К писку товаров</a>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/products_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <p class="lead text-body-secondary">
                    Здесь Вы можете посмотреть все товары, представленные в нашем интернет-магазине,
                    а так же перейти на страницу интересующего Вас товара и в категорию товара.
                        <p>Так же Вы можете
                            <a type="button" class="btn btn-link"
                               href="{% url 'catalog:product_create' %}">Предложить свой товар</a>
                        </p>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for object in object_list %}

                    <div class="col">
                        <div class="card shadow-sm" style="width: 18rem;">
                            <img src="{{ object.img|mymedia }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <p class="card-text">
                                    {% if object.is_published %}
                                        {{ object|title }}
                                    {% else %}
                                        <span class="text-muted">{{ object|title }}</span>
                                    {% endif %}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a type="button" class="btn btn-sm btn-outline-secondary"
                                           href="{% url 'catalog:product_detail' object.pk %}">К товару</a>
                                        <a type="button" class="btn btn-sm btn-outline-secondary"
                                           href="{% url 'catalog:product_card' object.pk %}">К категории</a>
                                        <a type="button" class="btn btn-sm btn-outline-secondary" href="#">В корзину</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/review_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container col-3">
            <div class="row">
                <div class="col-auto">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить отзыв "{{ object.title }}"?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'catalog:reviews' %}" class="btn btn-success">Отменить</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/review_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ object.title }}</h1>
            </div>
        </div>
    </section>
    <div class="container">
        <div class="row g-0 bg-body-secondary position-relative">
            <div class="col-md-6 mb-md-0 p-md-4">
                <img src="{{ object.photo|mymedia }}" class="w-100" alt="...">
            </div>
            <div class="col-md-6 p-4 ps-md-0">
                <h5 class="mt-0">Slug: {{ object.slug }}</h5>
                <p>Текст: {{ object.text }}</p>
                <p>Дата публикации: {{ object.creation_date }}</p>
                <a type="button" class="btn btn-primary" href="{% url 'catalog:reviews' %}">К отзывам</a>
                {% if object.user == request.user or user.is_superuser or user.is_staff %}
                    {% if perms.catalog.change_review %}
                        <a type="button" class="btn btn-warning" href="{% url 'catalog:review_edit' object.pk %}">Редактировать</a>
                    {% endif %}
                {% endif %}
                {% if user.is_superuser %}
                    <a type="button" class="btn btn-danger"
                       href="{% url 'catalog:delete_review' object.pk %}">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}